//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuorisoTaloKortti.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Huoltajat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Huoltajat()
        {
            this.Nuoret = new HashSet<Huoltajat>();
        }

        public int HuoltajaId { get; set; }
        [Required(ErrorMessage = "Kenttä Etunimi on pakollinen tieto!")]
        public string Etunimi { get; set; }
        [Required(ErrorMessage = "Kenttä Sukunimi on pakollinen tieto!")]
        public string Sukunimi { get; set; }
        [Required(ErrorMessage = "Kenttä Puhelinnumero on pakollinen tieto!")]
        public string Puhelinnumero { get; set; }
        [Required(ErrorMessage = "Kenttä Osoite on pakollinen tieto!")]
        public string Osoite { get; set; }
        [Required(ErrorMessage = "Kenttä Sukunimi on pakollinen tieto!")]

        public string Postinumero { get; set; }

        public virtual Postitoimipaikat Postitoimipaikat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Huoltajat> Nuoret { get; set; }
    }
}
