//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuorisoTaloKortti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Huoltajat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Huoltajat()
        {
            this.Nuoret = new HashSet<Nuoret>();
        }
    
        public int HuoltajaId { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Puhelinnumero { get; set; }
        public string Osoite { get; set; }
        public string Postinumero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nuoret> Nuoret { get; set; }
    }
}
