//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuorisoTaloKortti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayttajat
    {
        public int KayttajaId { get; set; }
        public string Kayttajanimi { get; set; }
        public string Salasana { get; set; }
        public bool Admin { get; set; }
    }
}
