//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuorisoTaloKortti.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NuorisokorttiEntities : DbContext
    {
        public NuorisokorttiEntities()
            : base("name=NuorisokorttiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Huoltajat> Huoltajat { get; set; }
        public virtual DbSet<Kayttajat> Kayttajat { get; set; }
        public virtual DbSet<Nuoret> Nuoret { get; set; }
        public virtual DbSet<Postitoimipaikat> Postitoimipaikat { get; set; }
    }
}
