//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuorisoTaloKortti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nuoret
    {
        public int NuoriId { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public System.DateTime SyntymaAika { get; set; }
        public string Puhelinnumero { get; set; }
        public string Osoite { get; set; }
        public string Postinumero { get; set; }
        public int Huoltaja { get; set; }
        public string SPosti { get; set; }
        public string Allergiat { get; set; }
        public bool Kuvauslupa { get; set; }
        public bool Aktivointi { get; set; }
        public byte[] Kuva { get; set; }
        public string Kayttajanimi { get; set; }
    
        public virtual Huoltajat Huoltajat { get; set; }
    }
}
